# Cluster ingress for the CLI endpoint
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - host: cli.rocketship.sh
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: rocketship-cloud-tls
      hosts:
        - cli.rocketship.sh
engine:
  image:
    repository: rocketshipai/rocketship-engine
    tag: v0.5.28
worker:
  image:
    repository: rocketshipai/rocketship-worker
    tag: v0.5.28
auth:
  broker:
    image:
      repository: rocketshipai/rocketship-auth-broker
      tag: v0.5.28
